apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: vybes-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vybes-api-gateway
  template:
    metadata:
      labels:
        app: vybes-api-gateway
    spec:
      containers:
        - name: vybes-api-gateway
          image: pimvanhooren/vybes-api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: vybes-api-gateway
  ports:
    - protocol: TCP
      port: 5086
      targetPort: 80
  type: LoadBalancer