apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vybes-rabbit
  template:
    metadata:
      labels:
        app: vybes-rabbit
    spec:
      containers:
        - name: vybes-rabbit
          image: rabbitmq:3-management
          ports:
            - containerPort: 15672
              name: rbmq-mgmt-port
            - containerPort: 5672
              name: rbmq-msg-port
          env:
            - name: "RABBITMQ_DEFAULT_USER"
              value: "guest"
            - name: "RABBITMQ_DEFAULT_PASS"
              value: "Pimpas123"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: vybes-rabbit
  ports:
    - name: rbmq-mgmt-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rbmq-msg-port
      protocol: TCP
      port: 5672
      targetPort: 5672
